In [1]:
import numpy as np

In [6]:
a = np.array([1, 2, 3])
print(type(a))
print(a.dtype)
print(a.shape)
print(a.ndim)
print(a.size)
print(a.itemsize)
print(a.nbytes)
print(a.flags)

<class 'numpy.ndarray'>
int64
(3,)
1
3
8
24
  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False



In [8]:
b = np.array([[1, 2, 3], [4, 5, 6]])
print(b)
print(type(b))
print(b.dtype)
print(b.shape)
print(b.ndim)

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
int64
(2, 3)
2


In [9]:
c = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(c)
print(type(c))
print(c.dtype)
print(c.shape)
print(c.ndim)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
<class 'numpy.ndarray'>
int64
(2, 2, 3)
3
